version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s %(pathname)s(line:%(lineno)d): %(levelname)s %(message)s"

handlers:
    console_handler:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
    file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs/test.log
        when: d
        backupCount: 7
        encoding: utf-8

loggers:
    console_and_file:
        level: INFO
        handlers: [console_handler, file_handler]